// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function GetLogs():Promise<string>;

export function GetState():Promise<main.AppState>;

export function SetAutoFix(arg1:boolean):Promise<main.AppState>;

export function SetAutoStart(arg1:boolean):Promise<main.AppState>;

export function SetCaptureLogs(arg1:boolean):Promise<main.AppState>;

export function SetSilentStart(arg1:boolean):Promise<main.AppState>;

export function SilentStart():Promise<boolean>;
