// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function SetAutoFix(arg1) {
  return window['go']['main']['App']['SetAutoFix'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetCaptureLogs(arg1) {
  return window['go']['main']['App']['SetCaptureLogs'](arg1);
}

export function SetSilentStart(arg1) {
  return window['go']['main']['App']['SetSilentStart'](arg1);
}

export function SilentStart() {
  return window['go']['main']['App']['SilentStart']();
}
